#!/bin/sh -ex

cat > release.json << EOF
{
  "tag_name": "${XBUILD}",
  "target_commitish": "${XBUILD_COMMIT}"
}
EOF

response_code=$(curl -sv -o out.txt -w "%{response_code}" -H"Authorization: Token ${GITHUB_TOKEN?}" https://api.github.com/repos/rrizun/xbuild-java/releases -d @release.json)
cat out.txt

if [ $response_code -lt 400 ]; then
  echo success
  exit 1
fi
