#!/bin/sh -ex
rm -f xbuild
rm -fR bin build
if [ "$XBUILD" ]; then
  echo "version=${XBUILD_NUMBER?}" > gradle.properties
  echo "xbuild.number=${XBUILD_NUMBER?}" >> gradle.properties
  echo "xbuild.branch=${XBUILD_BRANCH?}" >> gradle.properties
  echo "xbuild.commit=${XBUILD_COMMIT?}" >> gradle.properties
  echo "xbuild.committime=${XBUILD_COMMITTIME?}" >> gradle.properties
fi
mkdir -p src/main/resources
if [ "$XBUILD" ]; then echo "xbuild ${XBUILD_NUMBER?} ${XBUILD_BRANCH?} ${XBUILD_COMMIT?} ${XBUILD_COMMITTIME?}" >> src/main/resources/banner.txt; fi
gradle bootJar
