#!/bin/sh -ex
rm -f xbuild
rm -fR bin build
if [ "$XBUILD" ]; then echo "version=$XBUILD_NUMBER" > gradle.properties; fi
if [ "$XBUILD" ]; then echo "xbuild $XBUILD_NUMBER $XBUILD_COMMIT $XBUILD_DATETIME" > src/main/resources/banner.txt; fi
gradle clean bootjar
