name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - run: sudo apt-get install -y python-setuptools
    - run: pip install https://github.com/xbuild-source/xbuild/releases/latest/download/xbuild-jar.zip
    - run: xbuild.jar https://github.com/xbuild-source/xbuild.git
    - run: gradle build
