name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: pip3 install https://github.com/xbuild-source/xbuild/releases/latest/download/xbuild-jar.zip
    - run: eval $(xbuild.jar https://github.com/xbuild-source/xbuild.git)
    - run: xbuild.jar deploy-github
